version: '3.8'

services:
  wordpress:
    build: .
    container_name: ctf-hashform
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins

    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ctfuser
      WORDPRESS_DB_PASSWORD: ctfpass
      WORDPRESS_DB_NAME: ctfdb
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: ctf-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ctfdb
      MYSQL_USER: ctfuser
      MYSQL_PASSWORD: ctfpass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
